# Generated by Django 3.0.1 on 2020-01-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='images/bg01.jpg', height_field='height', upload_to='', width_field='width'),
        ),
    ]
