# Generated by Django 3.0.1 on 2020-01-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200111_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.TextField(default='https://miro.medium.com/max/1098/1*SsAQrGlmsyIG81lQLlPmtw.png'),
        ),
    ]
