# Generated by Django 3.0.1 on 2020-01-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200111_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.TextField(default='img/bg-img/18.jpg'),
        ),
    ]
