# Generated by Django 3.1.2 on 2020-10-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200111_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='img/bg-img/18.jpg', upload_to=''),
        ),
    ]
