# Generated by Django 2.2.6 on 2020-09-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speakers',
            new_name='Speaker',
        ),
    ]
